server:
  port: 7081
  servlet:
    context-path: /neo4j

# neo4j
spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: 123456
#      上传文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB